In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

## Array Calculation Methods

### `sum` function

In [7]:
a = np.arange(1,7)
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

**`sum()` defaults to adding up all the values in an array**

In [8]:
np.sum(a)

21

**supply the keyword `axis=0` to sum along the 0th axis**

In [9]:
np.sum(a, axis=0)

array([5, 7, 9])

**supply the keyword `axis=-1` to sum along the last axis**

In [10]:
np.sum(a, axis=-1)

array([ 6, 15])

### `sum` array method

**`a.sum()` defaults to adding up all values in an array**

In [11]:
a.sum()

21

**supply an axis argument to sum along a specific axis (same as `np.sum()`)**

In [12]:
a.sum(axis=0)

array([5, 7, 9])

In [13]:
a.sum(axis=-1)

array([ 6, 15])

### Product (`prod`)

** product along columns**

In [14]:
a.prod(axis=0)

array([ 4, 10, 18])

**functional form**

In [15]:
np.prod(a, axis=0)

array([ 4, 10, 18])

## Min/Max

### `min`

In [16]:
a = np.array([2., 3., 0., 1.])
a.min(axis=0)

0.0

**`np.amin()` and `np.min()` appear to be identical**

(**`from numpy import *`** apparently purposely doesn't import `np.min` or `np.max` into namespace)

In [19]:
np.amin

<function numpy.core.fromnumeric.amin>

In [20]:
np.min

<function numpy.core.fromnumeric.amin>

** Use NumPy's `amin()` instead of Python's build-in `min()` for speedy operations on multi-dimensional arrays.**

In [21]:
np.amin(a, axis=0)

0.0

### `argmin`

**find index of minimum value**

In [22]:
a.argmin(axis=0)

2

**functional form**

In [23]:
np.argmin(a, axis=0)

2

### `max`

In [24]:
a = np.array([2., 3., 0., 1.])
a.max(axis=0)

3.0

**functional form**

In [25]:
np.amax(a, axis=0)

3.0

### `argmax`

**find index of maximum value**

In [26]:
a.argmax(axis=0)

1

**functional form**

In [27]:
np.argmax(a, axis=0)

1

## Statistics Array Methods

### `mean`

In [28]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

**mean value of each column**

In [29]:
a.mean(axis=0)

array([ 2.5,  3.5,  4.5])

In [30]:
np.mean(a, axis=0)

array([ 2.5,  3.5,  4.5])

In [31]:
np.average(a, axis=0)

array([ 2.5,  3.5,  4.5])

**`average` can also calculate a *weighted* average**

In [32]:
np.average(a, 
           weights=[1,2], 
           axis=0)

array([ 3.,  4.,  5.])

### standard deviation / variance

**Standard Deviation**

In [36]:
a.std(axis=0)

array([ 1.5,  1.5,  1.5])

In [37]:
np.std(a, axis=0)

array([ 1.5,  1.5,  1.5])

**variance**

In [34]:
a.var(axis=0)

array([ 2.25,  2.25,  2.25])

In [35]:
np.var(a, axis=0)

array([ 2.25,  2.25,  2.25])

## Other Array Methods

### `clip`

**Limit values to a range**

In [38]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

**set values < 3 equal to 3, set values > 5 equal to 5**

In [39]:
a.clip(3, 5)

array([[3, 3, 3],
       [4, 5, 5]])

### Peak to Peak -- `ptp`

**Calculate (max - min) for array along columns**

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a.ptp(axis=0)

array([3, 3, 3])

**(max - min) for entire array**

In [41]:
a.ptp(axis=None)

5

### `round`

**Round values in an array. NumPy rounds to even, so *1.5 and 2.5 both round to 2***

In [43]:
a = np.array([1.35, 2.5, 1.5])
a

array([ 1.35,  2.5 ,  1.5 ])

In [44]:
a.round()

array([ 1.,  2.,  2.])

**Round to first decimal place**

In [45]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])