In [1]:
import numpy as np

In [2]:
# Simple array creation

a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [3]:
# checking type
type(a)

numpy.ndarray

In [4]:
# numeric 'type' of elements -- the more interesting "type"

a.dtype

dtype('int64')

In [5]:
# bytes per element
a.itemsize

8

In [6]:
# array shape

print(a.shape)

print(np.shape(a))

(4,)
(4,)


In [7]:
# Size reports the entire number of elements in an array

print(a.size)

print(np.size(a))

4
4


In [8]:
# bytes of memory used

# return the number of bytes used by the data portion of the array

a.nbytes

32

In [9]:
# number of dimensions

a.ndim

1

In [10]:
# array indexing

# standard 0-based indexing

print(a[0])

a[0] = 10

print(a)

0
[10  1  2  3]


In [11]:
# fill

# set all values in an array

a.fill(0)
print(a)

# this also works, but may be slower

a[:] = 1
print(a)

[0 0 0 0]
[1 1 1 1]


In [12]:
# Beware of type coercion

print(a.dtype)

# assigning a float into an int32 array truncates the decimal part
a[0] = 10.6
print(a)

# fill has the same behavior
a.fill(-4.8)
print(a)

int64
[10  1  1  1]
[-4 -4 -4 -4]


## Slicing

`var[lower:upper:step]`

Extracts a portion of a sequence by specifying a lower and upper bound.

**The lower-bound element *is* included, but the upper-bound element is *not* included.**

Mathematically: [lower, upper]. The step value specifies the ***stride*** between elements.

In [14]:
# Slicing arrays

# indices: 0 1 2 3 4

a = np.array([10,11,12,13,14])
a[1:3]

array([11, 12])

In [15]:
# negative indices work also

print(a[1:-2])

print(a[-4:3])

[11 12]
[11 12]


In [18]:
# omitting indices

# omitted boundaries are assumed to be the beginning (or end) of the list

print('full array', a)

# grab first three elements
print('first three', a[:3])

# grab last two elements
print('last two', a[-2:])

# every other element
print('every other element', a[::2])

# every other element, odd elements
print('every other element (odds)', a[1::2])

full array [10 11 12 13 14]
first three [10 11 12]
last two [13 14]
every other element [10 12 14]
every other element (odds) [11 13]


### sum vs. cumsum

In [20]:
print('array a', a)
print('sum(a)', np.sum(a)) # returns a scalar
print('cumsum(a)', np.cumsum(a)) # returns an array where each element is the sum of the previous elements

array a [10 11 12 13 14]
sum(a) 60
cumsum(a) [10 21 33 46 60]
