In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## "Flattening" arrays

### `flatten`

method converts a multi-dimensional array into a 1D array (creates a **copy**)

In [2]:
a = np.array([[0, 1],
              [2, 3]
             ])

print(a)

b = a.flatten()
b

[[0 1]
 [2 3]]


array([0, 1, 2, 3])

**changing b does not change a**

In [3]:
b[0] = 10
print(b)

print(a)

[10  1  2  3]
[[0 1]
 [2 3]]


### `flat`

an **attribute** that returns an *iterator object* that accesses the data in a **multi-dimensional array as a 1D array**. 

`flat` *references* the original memory.

In [4]:
a.flat

In [5]:
a.flat[:]

array([0, 1, 2, 3])

In [6]:
b = a.flat
b[0] = 10
a # now changed!

array([[10,  1],
       [ 2,  3]])

In [7]:
for item in a:
    print('item', item)

item [10  1]
item [2 3]


In [8]:
for item in a.flat:
    print('item', item)

item 10
item 1
item 2
item 3


## "(Un)raveling" Arrays

### `ravel`

same as **`flatten`** but returns a *reference* (view) of the array, if possible (if the memory is contiguous). Otherwise, new array copies the data.

In [9]:
a = np.array([[0, 1],
              [2, 3]
             ])

# flatten out elements to 1D

b = a.ravel()
b

array([0, 1, 2, 3])

**changing b *does* change a**

In [10]:
b[0] = 10
b

array([10,  1,  2,  3])

In [11]:
a

array([[10,  1],
       [ 2,  3]])

### when `ravel` makes a *copy*

In [12]:
a = np.array([[0, 1],
              [2, 3]
             ])
a

array([[0, 1],
       [2, 3]])

***`transpose` array so memory layout is no longer contiguous***

In [13]:
aa = a.transpose()
aa

array([[0, 2],
       [1, 3]])

**`ravel` creates a copy of data *in this case* **

In [14]:
b = aa.ravel()
b

array([0, 2, 1, 3])

**changing b (in this case) *doesn't* change a**

In [15]:
b[0] = 10
b

array([10,  2,  1,  3])

In [16]:
a

array([[0, 1],
       [2, 3]])

## Reshaping Arrays

### `shape`

In [17]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a.shape

(6,)

**reshape array *in-place* to 2x3**

In [19]:
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

### `reshape`

returns a **new** array with a different shape

In [20]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

reshape cannot change *the number of elements* in an array

**`a.reshape(4,2)`**

`---------------------------------------------------------------------------`

`ValueError                                Traceback (most recent call last)`

`<ipython-input-24-1a35a76a1693> in <module>()`

`----> 1 a.reshape(4,2)`

`ValueError: total size of new array must be unchanged`


## Transpose

### `transpose`

swaps the order of axes. For 2D, this swaps rows and columns.

In [21]:
a = np.array([[0, 1, 2],
              [3, 4, 5]
             ])
a.shape

(2, 3)

In [22]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

the **`.T`** attribute is equivalent to `transpose()`

In [23]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

`transpose()` returns **views**

In [24]:
b = a.T
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [25]:
b[0,1] = 30
a

array([[ 0,  1,  2],
       [30,  4,  5]])

### `transpose` and `strides`

`transpose` does not move values around in memory. It only changes the order of `strides` in the array.

In [26]:
a.strides

(24, 8)

In [27]:
a.T.strides

(8, 24)

## Indexing with `newaxis`

`newaxis` is a **special index** that inserts a **new axis** in the array at the specified location

each `newaxis` increases the array's dimensionality by 1

In [28]:
a = np.array([0, 1, 2])
print(a)
a.shape

[0 1 2]


(3,)

In [29]:
y = a[np.newaxis, :]
print(y)
y.shape

[[0 1 2]]


(1, 3)

In [30]:
y = a[:, np.newaxis]
print(y)
y.shape

[[0]
 [1]
 [2]]


(3, 1)

In [31]:
y = a[np.newaxis, np.newaxis, :]
print(y)
y.shape

[[[0 1 2]]]


(1, 1, 3)

### `squeeze`

removes "unnecessary" dimensions

In [32]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

**insert an "extra" dimension**

In [33]:
a.shape = (2, 1, 3)
a

array([[[1, 2, 3]],

       [[4, 5, 6]]])

**`squeeze` removes any dimension with length == 1**

In [34]:
a = a.squeeze()
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

## Diagonals

### `diagonal`

In [35]:
a = np.array([[11, 21, 31],
              [12, 22, 32],
              [13, 23, 33]])
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

**extract the diagonal from an array**

In [36]:
a.diagonal()

array([11, 22, 33])

** use *offset* to move off the main diagonal** (offset can be negative)

In [37]:
a.diagonal(offset=1)

array([21, 32])

### diagonals with indexing

"fancy" indexing also works

In [38]:
i = [0, 1, 2]
a[i, i]

array([11, 22, 33])

**indexing can also be used to set diagonal values**

In [39]:
a[i, i] = 2
i2 = np.array([0,1])
i2

array([0, 1])

**upper diagonal**

In [40]:
a[i2, i2+1] = 1
a

array([[ 2,  1, 31],
       [12,  2,  1],
       [13, 23,  2]])

**lower diagonal**

In [41]:
a[i2+1, i2] = -1
a

array([[ 2,  1, 31],
       [-1,  2,  1],
       [13, -1,  2]])

## Complex Numbers

### Complex Array Attributes

In [42]:
a = np.array([1+1j, 2, 3, 4])
a

array([ 1.+1.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [43]:
a.dtype

dtype('complex128')

**real and imaginary parts**

In [44]:
a.real

array([ 1.,  2.,  3.,  4.])

In [45]:
a.imag

array([ 1.,  0.,  0.,  0.])

**set imaginary part to a different set of values**

In [46]:
a.imag = (1,2,3,4)
a

array([ 1.+1.j,  2.+2.j,  3.+3.j,  4.+4.j])

**conjugation**

In [47]:
a.conj()

array([ 1.-1.j,  2.-2.j,  3.-3.j,  4.-4.j])

**float (and other) arrays**

In [48]:
a = np.array([0., 1, 2, 3])
a

array([ 0.,  1.,  2.,  3.])

**`.real` and `.imag` attributes are available**

In [49]:
a.real

array([ 0.,  1.,  2.,  3.])

In [50]:
a.imag

array([ 0.,  0.,  0.,  0.])

**...but `.imag` *(in this case)* is read-only**

    a.imag = (1,2,3,4)

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-54-94524e0cfbcd> in <module>()
    ----> 1 a.imag = (1,2,3,4)

    TypeError: array does not have imaginary part to set


## Array Constructor Examples

### floating point arrays

default to double precision

In [51]:
a = np.array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

In [52]:
a.nbytes

32

**reducing precision**

In [53]:
a = np.array([0, 1.0, 2, 3], dtype=np.float32)
a.dtype

dtype('float32')

In [54]:
a.nbytes

16

**unsigned integer byte**

In [55]:
a = np.array([0, 1, 2, 3], dtype=np.uint8)
a.dtype

dtype('uint8')

In [56]:
a.nbytes

4

**array from binary data**

In [57]:
# a = np.frombuffer('foo', dtype=np.uint8)
# a

**reverse operation**

In [58]:
a.tofile('foo.dat')

In [59]:
!rm foo.dat

## Specifying DTypes

### Default (by inspection)

**float --> np.float64**

In [60]:
a = np.array([0, 1.0, 2, 3])
a.dtype

dtype('float64')

**int --> np.int64**

In [61]:
b = np.array([0, 1, 2, 3])
b.dtype

dtype('int64')

### Python Data Types

**float --> np.float64**

In [62]:
c = np.array([0, 1, 2, 3], dtype=float)
c.dtype

dtype('float64')

### NumPy Data Types

In [63]:
d = np.array([0,1,2,3], dtype=np.uint8)
d.dtype

dtype('uint8')

### String specification

**Big-Endian float, 8 bytes**

In [64]:
e = np.array([0,1,2,3], dtype='>f8')
e.dtype

dtype('>f8')

**strings of length 8**

In [65]:
# default
f = np.array(["01234567"])
f.dtype

dtype('<U8')

In [66]:
f = np.array(["01234567"], dtype="S8")
f.dtype

dtype('S8')

## Typecasting

### `asarray`

In [67]:
a = np.array([1.5, -3], dtype=np.float32)
a

array([ 1.5, -3. ], dtype=float32)

**upcast**

In [68]:
np.asarray(a, dtype=np.float64)

array([ 1.5, -3. ])

**downcast**

In [69]:
np.asarray(a, dtype=np.uint8)

array([  1, 253], dtype=uint8)

**`asarray` is efficient. It *does not* make a copy if the type is the same.**

In [70]:
b = np.asarray(a, dtype=np.float32)
b[0] = 2.0
a

array([ 2., -3.], dtype=float32)

### `astype`

In [71]:
a = np.array([1.5, -3], dtype=np.float64)
a.astype(np.float32)

array([ 1.5, -3. ], dtype=float32)

In [72]:
a.astype(np.uint8)

array([  1, 253], dtype=uint8)

**`astype` is *safe*. It always returns a *copy* of the array.**

In [73]:
b = a.astype(np.float64)
b[0] = 2.0
a

array([ 1.5, -3. ])